### ISSUE TITLE
Until swing UI available ... could you provide an annotated screenshot with labels to the settings in the `.json` ?

### ISSUE THREAD

**Issue by grymmjack** [Berikai/bitwig-theme-editor#3]
Hi,

Thanks for making this!

Could you possibly create an annotated screenshot with labels on it that correspond to the related setting in the `.json` of the theme so we could start getting building our own without waiting for the GUI?

Also, after we make a change to the theme, we have to restart bitwig right? We can't edit these themes in real time?

Thank you again for making this!

**Comment by Berikai** [comment]
Hi,

I also don't know what each of the values correspond to. There are approximately 250 values that should be figured out. Although I'm planning to provide an annotated guide at some point, it may take time. It would be great if community members participate on this 🫶🏼

Yes, you have to restart after every theme change you made. It is not possible to edit themes in real time currently.

**Comment by deusnovus** [comment]
For anyone searching for this thread: I have started [a public Google spreadsheet]([https://docs.google.com/spreadsheets/d/1iDRYxo2RMPbe8ldjIJqW2GKF_mb1Ldy4Fg6RKudc5jI/edit?](https://docs.google.com/spreadsheets/d/1iDRYxo2RMPbe8ldjIJqW2GKF_mb1Ldy4Fg6RKudc5jI/edit?gid=1944421253#gid=1944421253)), feel free to populate it with all your findings and help Berikai with developing his editor.

We have tabs for window parameters, arrangement parameters and uneditable parameters.

**Comment by Vondersulzburg** [comment]
Can you mark the background of the arrangement in the EXCEL. I would set it to a lighter nearly white color. I just start next week to mod and then would set my remarks. Is it intended to add screen shots to the EXCEL to describe the parameter or will this lead to a much too big EXCEL?

Danke

Michael
