### ISSUE TITLE
Audio Event & MIDI Event transparency

### ISSUE THREAD

**Issue by loaykhalifa** [Berikai/bitwig-theme-editor#4]
First of all thank you for making that
The question:
Can this adjust an Audio Event or MIDI Event transparency ?

**Comment by Berikai** [comment]
Currently, I don't know what each value correspond to but there is a community effort of documenting them in the Bitwig Community Discord.
  
> For anyone searching for this thread: I have started [a public Google spreadsheet](https://docs.google.com/spreadsheets/d/1iDRYxo2RMPbe8ldjIJqW2GKF_mb1Ldy4Fg6RKudc5jI/edit?gid=1944421253#gid=1944421253), feel free to populate it with all your findings and help Berikai with developing his editor.
> 
> We have tabs for window parameters, arrangement parameters and uneditable parameters.



_Originally posted by @deusnovus in https://github.com/Berikai/bitwig-theme-editor/issues/3#issuecomment-2169214116_
